### ISSUE TITLE
Where is "advanced" mode under Adobe?

### ISSUE THREAD

**Issue by SHxKM** [morris/typekit-cache#20]
This is more of a question than anything else. I've stumbled across this repo while looking for caching solutions for Adobe Fonts (which TypeKit is part of now). I'm currently including a  reference to the css files like so:

```HTML
<link rel="stylesheet" href="https://use.typekit.net/XXXXXX.css">
```

So it's unclear to me which advanced mode this line in the README refers to:

> Copy the contents of typekit-cache.min.js right before your Typekit (advanced) embed code

Thanks for your work!

**Comment by morris** [comment]
Hi, thanks for reporting this! typekit-cache was developed at a time when including Typekits was done using a JavaScript snippet (called "advanced embed code"), so typekit-cache is currently only applicable to older TypeKit installations. Since they switched to a simple CSS include, typekit-cache will not have any effect when using the new method, unfortunately.

A way forward would be service worker caching, in effect making the included CSS and fonts available "offline". I will give it a shot this week. Thanks again!

**Comment by morris** [comment]
I believe regular browser caching should apply though, so maybe there is no way to improve after the first page load. Need to test if there's any possible benefit first.

**Comment by SHxKM** [comment]
Thanks for taking the time to respond @morris. You can close this if there’s no resolution planned.

**Comment by morris** [comment]
As it stands now, typekit-cache only works for older Typekit installations (using JavaScript). Newer installations use a `<link>` tag and all referenced resources are cached properly, i.e. served from disk on a user's next visit. This cannot be further improved, so upgrading to the `<link>` and removing typekit-cache is recommended!
